pimcore_data_hub:
    configurations:
        meds:
            general:
                type: dataImporterDataObject
                name: meds
                description: ''
                group: ''
                active: false
                path: null
                modificationDate: 1678791150
                createDate: 1678747014
            loaderConfig:
                type: asset
                settings:
                    assetPath: /Rejestr_Produktow_Leczniczych.csv
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ;
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '2'
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /medicines
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                cleanup:
                    strategy: unpublish
            mappingConfig:
                -
                    label: 'Identyfikator Produktu Leczniczego [0]'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: sku
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Nazwa Produktu Leczniczego [1]'
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Nazwa powszechnie stosowana [2]'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: commonName
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Rodzaj preparatu [3]'
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: preparatType
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Nazwa poprzednia produktu [4]'
                    dataSourceIndex:
                        - '4'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: oldName
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Gatunki docelowe [5]'
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: targetSpecies
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Okres karencji [6]'
                    dataSourceIndex:
                        - '6'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: withdrawalPeriod
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Moc [7]'
                    dataSourceIndex:
                        - '7'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: strength
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Postać farmaceutyczna [8]'
                    dataSourceIndex:
                        - '8'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: dosageForm
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Typ procedury [9]'
                    dataSourceIndex:
                        - '9'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: procedureType
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Numer pozwolenia [10]'
                    dataSourceIndex:
                        - '10'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: licenceNumber
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'Ważność pozwolenia [11]'
                    dataSourceIndex:
                        - '11'
                    settings:
                        original: Bezterminowe
                        converted: '0'
                        format: d.m.Y
                    transformationResultType: date
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: licenceValidityDate
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                original: Bezterminowe
                                converted: '0'
                            type: conditionalConversion
                        -
                            settings:
                                format: d.m.Y
                            type: date
                -
                    label: 'Kod ATC [12]'
                    dataSourceIndex:
                        - '12'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: atcCode
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Opakowanie [14]'
                    dataSourceIndex:
                        - '14'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: packet
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Substancja czynna [15]'
                    dataSourceIndex:
                        - '15'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: activeIngredient
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user:
                    -
                        id: 2
                        name: admin
                        read: true
                        update: true
                        delete: true
                role: {  }
            workspaces: {  }
